version: "3"

services:
  mysql-backup-wp1:
    container_name: mysql-backup-wp1
    build:
      context: .
      args:
        MARIADB_VERSION: '11'
        TARGETARCH: "linux/arm64"
    environment:
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - AWS_DEFAULT_REGION=${S3_REGION}
      - AWS_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET_NAME}
      - S3_PREFIX=${BACKUP_PREFIX}/${WORDPRESS_DB_NAME}
      # Variabili MySQL
      - MYSQL_HOST=wp-db
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=3306
      - SCHEDULE=@every 3m
      - BACKUP_KEEP_DAYS=14
      - PASSPHRASE=${MYSQL_PASSWORD}
    networks:
      - traefik_default

  mysql-backup-wp2:
    container_name: mysql-backup-wp2
    build:
      context: .
      args:
        MARIADB_VERSION: '11'
        TARGETARCH: "linux/arm64"
    environment:
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - AWS_DEFAULT_REGION=${S3_REGION}
      - AWS_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET_NAME}
      - S3_PREFIX=${BACKUP_PREFIX}/${WORDPRESS_DB_NAME2}
      # Variabili MySQL
      - MYSQL_HOST=wp-db
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME2}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=3306
      - SCHEDULE=@every 5m
      - BACKUP_KEEP_DAYS=14
      - PASSPHRASE=${MYSQL_PASSWORD}
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true 