version: "3"
# this file is here to facilitate development/testing
# $ docker compose up -d --build --force-recreate

services:

  wp:
    image: wordpress:6-apache #fpm doesn't work
    container_name: wp
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./wp_data:/var/www/html
      # here also is the memory limit!!!
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - traefik_default
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_CHARSET: ${WORDPRESS_DB_CHARSET}
      WORDPRESS_DEBUG: 1
      #WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
    ports:
      - 80:80
    

  wp2:
    image: wordpress:6-apache #fpm doesn't work
    container_name: wp2
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./wp2_data:/var/www/html
      # here also is the memory limit!!!
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - traefik_default
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME2}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER2}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD2}
      WORDPRESS_DB_CHARSET: ${WORDPRESS_DB_CHARSET2}
      WORDPRESS_DEBUG: 1
      #WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
    ports:
      - 81:80


  wp-db:
    image: mariadb:11
    container_name: wp-db
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - traefik_default
    restart: unless-stopped
    # ports:
    #   - $MYSQL_PORT:$MYSQL_PORT
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: admin
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3


# volumes:
#   mysql_data:

networks:
  traefik_default:
    external: true
